[package]
name = "fomc_rates"
version = "0.1.0"
authors = []

[addresses]
# Overridden at compile/publish time with --named-addresses fomc_rates=<addr>
fomc_rates = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

# Liquidswap local dependency for router module used by real swaps
[dependencies.Liquidswap]
local = "external/liquidswap"

[dev-dependencies]
