[package]
name = 'supra'
version = '0.1.0'

[dependencies.SupraFramework]
git = 'https://github.com/Entropy-Foundation/aptos-core.git'
subdir = 'aptos-move/framework/supra-framework'
rev = 'dev'


[dependencies.dexlyn_swap]
git = 'https://github.com/DexlynLabs/dexlyn_swap_interface.git'
rev = 'testnet'

[dependencies.core]
git = "https://github.com/Entropy-Foundation/dora-interface"
subdir = "supra/testnet/core"
rev = "master"

[addresses]
fin_triggers = "0xb993b8afb07eadc713990f90ec5c422e664c13741dc0e932916a98863cd241a9"
